### ISSUE TITLE
pyzfs fails on OSX

### ISSUE THREAD

**Issue by kim0** [ClusterHQ/pyzfs#31] opened 2016-08-24 18:59 UTC
I'm trying to use pyzfs as a universal frontend to zfs on OSX, Linux and FreeBSD. Not really sure if it can/should work in this manner, but at least on my macbook I get the errors below. The ZFS implementation is https://openzfsonosx.org/ .. Any help is appreciated

```
$ python3
Python 3.5.2 (default, Jul 28 2016, 21:28:00)
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import libzfs_core as z
>>> z.lzc_list_snaps('zsource')
Traceback (most recent call last):
  File "/private/tmp/src/agent/lib/python3.5/site-packages/cffi/api.py", line 757, in _load_backend_lib
    raise OSError("library not found: %r" % (name,))
OSError: library not found: 'zfs_core'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/private/tmp/src/agent/lib/python3.5/site-packages/libzfs_core/_libzfs_core.py", line 720, in _f
    if not is_supported(_f):
  File "/private/tmp/src/agent/lib/python3.5/site-packages/libzfs_core/_libzfs_core.py", line 691, in is_supported
    return is_supported(check_func)
  File "/private/tmp/src/agent/lib/python3.5/site-packages/libzfs_core/_libzfs_core.py", line 692, in is_supported
    return getattr(_lib, fname, None) is not None
  File "/private/tmp/src/agent/lib/python3.5/site-packages/libzfs_core/_libzfs_core.py", line 1103, in __getattr__
    ret = self._lib.libzfs_core_init()
  File "/private/tmp/src/agent/lib/python3.5/site-packages/libzfs_core/bindings/__init__.py", line 28, in __getattr__
    self._lib = self._ffi.dlopen(self._libname)
  File "/private/tmp/src/agent/lib/python3.5/site-packages/cffi/api.py", line 139, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "/private/tmp/src/agent/lib/python3.5/site-packages/cffi/api.py", line 769, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "/private/tmp/src/agent/lib/python3.5/site-packages/cffi/api.py", line 764, in _load_backend_lib
    return backend.load_library(path, flags)
OSError: cannot load library /usr/local/lib/libzfs_core.dylib: dlopen(/usr/local/lib/libzfs_core.dylib, 2): Symbol not found: _zfs_flags
  Referenced from: /usr/local/lib/libzfs_core.dylib
  Expected in: flat namespace
 in /usr/local/lib/libzfs_core.dylib
```

**Comment by avg-I** [comment] 2016-09-05 10:47
@kim0 thank you for the report!
First, a note that the module was written for Python 2.7 and tested only with it. If it works with Python 3.x, then that's great, but there could be subtle problems.

This

```
OSError: cannot load library /usr/local/lib/libzfs_core.dylib: dlopen(/usr/local/lib/libzfs_core.dylib, 2): Symbol not found: _zfs_flags
  Referenced from: /usr/local/lib/libzfs_core.dylib
  Expected in: flat namespace
 in /usr/local/lib/libzfs_core.dylib
```

looks like a platform specific problem.
I wonder if in your environment `libzfs_core` has a dependency on another library.
Could you please check for that? I am not very familiar with OS X, is there a tool like `ldd`?

**Comment by avg-I** [comment] 2016-09-05 11:07
Looking at the _openzfsonosx_ code it seems that the problem is caused by the use of `dprintf` macro in lib/libzfs_core/libzfs_core.c. That macro references `zfs_flags` variable that is defined in `zfs_debug.c` and should be provided by `libzpool`.  For this reason `libzfs_core` should depend on `libzpool`, but there is no explicit dependency.

So, this is an  openzfsonosx problem.

Does OS X have something similar to `LD_PRELOAD`?
If yes, you could use that to pre-load `libzpool` and that should make things work.
Perhaps [DYLD_INSERT_LIBRARIES](https://blogs.oracle.com/DatabaseEmporium/entry/where_is_ld_preload_under) is it?

**Comment by lundman** [comment] 2016-09-06 00:10
> is there a tool like ldd?

`otool -L` would be the OSX equivalent.

> Does OS X have something similar to LD_PRELOAD? Perhaps DYLD_INSERT_LIBRARIES is it?

Yep, that would be the closest to `LD_PRELOAD`

Excellent debugging @avg-I - Really `libzfs_core` should not use `dprintf` at all, and those lines were left in after a big debugging session of OSX `ioctl` differences.

**Comment by avg-I** [comment] 2016-09-06 13:33
@lundman thank you for the information!
I am closing this issue.

**Closed as completed by avg-I** 2016-09-06 13:33 UTC
